var headerList =[
  {
    "key":'apiVersion'
    ,"type":'string'
    ,"title":'版本号'
    ,"desc":''
    ,"required":true
    ,"test-value":"1.2"
    ,"click":null
  }
  ,{
    "key":'userID'
    ,"type":'int'
    ,"title":'userID'
    ,"desc":''
    ,"required":true
    ,"test-value":"43756"
    ,"click":null
  }
  ,{
    "key":'time'
    ,"type":'string'
    ,"title":'time'
    ,"desc":''
    ,"required":true
    ,"test-value":""
    ,"click":function(){
      $(this).siblings("input").val((new Date()).getTime());
    }
  }
];
var apiList = [
      {
        "title":'example:test'
        ,"desc":''
        ,"action":'apitest.php'
        ,"method":"post"
        ,"request":[
          {
            "key":'name'
            ,"type":'string'
            ,"title":'name'
            ,"desc":''
            ,"required":true
            ,"test-value":"wanyaxing"
          }
          ,{
            "key":'password'
            ,"type":'md5'
            ,"title":'password'
            ,"desc":''
            ,"required":true
            ,"test-value":"123456"
          }
          ,{
            "key":'avatar'
            ,"type":'file'
            ,"title":'avatar'
            ,"desc":''
            ,"required":true
            ,"test-value":""
          }
          ,{
            "key":'age'
            ,"type":'int'
            ,"title":'age'
            ,"desc":''
            ,"required":true
            ,"test-value":"29"
          }
          ,{
            "key":'content'
            ,"type":'string'
            ,"title":'content'
            ,"desc":''
            ,"required":true
            ,"test-value":"see more detail , https://github.com/wanyaxing/apitest.php"
          }
        ]
      }
    ];
